import { Project, KPIData } from "./types";

// Mock data based on the Excel analysis - this will be replaced with Google Sheets API
export const projects: Project[] = [
  {
    id: 2337,
    projectName: "#2321 Choctaw Expansion Austin - Toni",
    location: "Oklahoma",
    projectAddress: "14237 SE 29th St Choctaw, OK 73020",
    projectLabel: "2025 Active project",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 480556.88,
    customer: "Austin McClune",
    phone: "(405) 623-7587",
    email: "mcclunecd@gmail.com",
    buildSize: "49,308 storage",
    receivedProjectDetails: "2025-05-07",
    zipCode: "73020",
    projectType: "Drive Up +CC",
    projectSQFT: 49306,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 636629.6,
    salesTaxPercent: 0.0975,
    ourQuoteWithTax: 698700.98,
    deliveredCustomerQuote: "2025-08-20",
    quoteAcceptedDeclined: "08/25/25",
    depositPaid: "Paid",
    engineeredDrawingsStatus: "Prelim Approved",
    estimatedMetalDeliveryDate: "2025-10-27",
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: "2025-12-15",
    metalProduction: "In production",
    metalDelivery: "Not Yet Delivered",
    doorDelivery: "Not Yet Shipped",
    finalACHPayment: null,
    contractorStartDate: "2025-09-08",
    jobStatus: "In the Works",
    comments: "Doug Gilland Owner - metal being delivered in stages",
  },
  {
    id: 2556,
    projectName: "#2543 24 Kitchen Pickle Ball-Toni",
    location: "Oklahoma",
    projectAddress: null,
    projectLabel: "2025 Active project",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 320000,
    customer: "Austin McClune",
    phone: "(405) 623-7587",
    email: "mcclunecd@gmail.com",
    buildSize: "24,000 sqft",
    receivedProjectDetails: "2025-06-01",
    zipCode: "73020",
    projectType: "Commercial",
    projectSQFT: 24000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 380000,
    salesTaxPercent: 0.0975,
    ourQuoteWithTax: 415000,
    deliveredCustomerQuote: "2025-07-15",
    quoteAcceptedDeclined: "Accepted",
    depositPaid: "Paid",
    engineeredDrawingsStatus: "In Progress",
    estimatedMetalDeliveryDate: "2025-11-15",
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: "2025-12-01",
    metalProduction: "Not Started",
    metalDelivery: "Not Yet Delivered",
    doorDelivery: "Not Yet Shipped",
    finalACHPayment: null,
    contractorStartDate: "2025-10-01",
    jobStatus: "In the Works",
    comments: null,
  },
  {
    id: 2944,
    projectName: "Garden Highway Self Storage",
    location: "California",
    projectAddress: "Garden Highway, Sacramento, CA",
    projectLabel: "2025 Active Bid",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 1450000,
    customer: "Rajvir Singh",
    phone: "(916) 555-1234",
    email: "rajvir@example.com",
    buildSize: "85,000 sqft",
    receivedProjectDetails: "2025-04-15",
    zipCode: "95833",
    projectType: "Drive Up +CC",
    projectSQFT: 85000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 1620000,
    salesTaxPercent: 0.0875,
    ourQuoteWithTax: 1776418,
    deliveredCustomerQuote: "2025-05-01",
    quoteAcceptedDeclined: "TBD",
    depositPaid: "Not Paid",
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: "Not Started",
    comments: "Large project - awaiting final approval",
  },
  {
    id: 2974,
    projectName: "#2965 South Austin Commerce Park 5 Bldgs",
    location: "Texas",
    projectAddress: "South Austin, TX",
    projectLabel: "2025 Active Bid",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 2100000,
    customer: "Clay Hundley",
    phone: "(512) 555-9876",
    email: "clay@example.com",
    buildSize: "120,000 sqft",
    receivedProjectDetails: "2025-03-20",
    zipCode: "78745",
    projectType: "Commercial",
    projectSQFT: 120000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 2280000,
    salesTaxPercent: 0.0825,
    ourQuoteWithTax: 2508000,
    deliveredCustomerQuote: "2025-04-10",
    quoteAcceptedDeclined: "TBD",
    depositPaid: "Not Paid",
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: "Not Started",
    comments: "5 building complex",
  },
  {
    id: 102,
    projectName: "Twinsburg OH",
    location: "Ohio",
    projectAddress: "Twinsburg, OH",
    projectLabel: "2025 New Lead",
    quoteSent: false,
    reachedOut: true,
    totalCOGs: 380000,
    customer: "Bruce Baum",
    phone: "(330) 555-4567",
    email: "bruce@example.com",
    buildSize: "35,000 sqft",
    receivedProjectDetails: null,
    zipCode: "44087",
    projectType: "Drive Up",
    projectSQFT: 35000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 400000,
    salesTaxPercent: 0.0725,
    ourQuoteWithTax: 438743.52,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 118,
    projectName: "Springfield TN",
    location: "Tennessee",
    projectAddress: "Springfield, TN",
    projectLabel: "2025 New Lead",
    quoteSent: false,
    reachedOut: false,
    totalCOGs: null,
    customer: "John Warner",
    phone: "(615) 555-7890",
    email: "john@example.com",
    buildSize: null,
    receivedProjectDetails: null,
    zipCode: "37172",
    projectType: null,
    projectSQFT: null,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: null,
    salesTaxPercent: null,
    ourQuoteWithTax: null,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 130,
    projectName: "Walterboro SC",
    location: "South Carolina",
    projectAddress: "Walterboro, SC",
    projectLabel: "2025 New Lead",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 120000,
    customer: "Ken Holmes",
    phone: "(843) 555-2345",
    email: "ken@example.com",
    buildSize: "12,000 sqft",
    receivedProjectDetails: "2025-02-10",
    zipCode: "29488",
    projectType: "Drive Up",
    projectSQFT: 12000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 127000,
    salesTaxPercent: 0.08,
    ourQuoteWithTax: 139219.56,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 143,
    projectName: "Oak Grove OK",
    location: "Oklahoma",
    projectAddress: "Oak Grove, OK",
    projectLabel: "2025 New Lead",
    quoteSent: false,
    reachedOut: true,
    totalCOGs: null,
    customer: "CSFill LLC",
    phone: "(405) 555-6789",
    email: "csfill@example.com",
    buildSize: null,
    receivedProjectDetails: null,
    zipCode: "73041",
    projectType: null,
    projectSQFT: null,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: null,
    salesTaxPercent: null,
    ourQuoteWithTax: null,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 156,
    projectName: "Mchenry IL",
    location: "Illinois",
    projectAddress: "McHenry, IL",
    projectLabel: "2025 New Lead",
    quoteSent: false,
    reachedOut: false,
    totalCOGs: null,
    customer: "Shane Long",
    phone: "(815) 555-3456",
    email: "shane@example.com",
    buildSize: null,
    receivedProjectDetails: null,
    zipCode: "60050",
    projectType: null,
    projectSQFT: null,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: null,
    salesTaxPercent: null,
    ourQuoteWithTax: null,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 169,
    projectName: "Coshocton OH",
    location: "Ohio",
    projectAddress: "Coshocton, OH",
    projectLabel: "2025 New Lead",
    quoteSent: false,
    reachedOut: true,
    totalCOGs: null,
    customer: "Steve Baldwin",
    phone: "(740) 555-8901",
    email: "steve@example.com",
    buildSize: null,
    receivedProjectDetails: null,
    zipCode: "43812",
    projectType: null,
    projectSQFT: null,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: null,
    salesTaxPercent: null,
    ourQuoteWithTax: null,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 182,
    projectName: "Norfolk NE",
    location: "Nebraska",
    projectAddress: "Norfolk, NE",
    projectLabel: "2025 Active Bid",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 550000,
    customer: "Kyle Deets",
    phone: "(402) 555-4321",
    email: "kyle@example.com",
    buildSize: "45,000 sqft",
    receivedProjectDetails: "2025-03-15",
    zipCode: "68701",
    projectType: "Drive Up +CC",
    projectSQFT: 45000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 580000,
    salesTaxPercent: 0.055,
    ourQuoteWithTax: 611900,
    deliveredCustomerQuote: "2025-04-01",
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 223,
    projectName: "Omaha NE",
    location: "Nebraska",
    projectAddress: "Omaha, NE",
    projectLabel: "2025 Active Bid",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 2800000,
    customer: "Joe Fisher",
    phone: "(402) 555-6543",
    email: "joe@example.com",
    buildSize: "150,000 sqft",
    receivedProjectDetails: "2025-02-28",
    zipCode: "68102",
    projectType: "Commercial",
    projectSQFT: 150000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 2900000,
    salesTaxPercent: 0.055,
    ourQuoteWithTax: 3041000,
    deliveredCustomerQuote: "2025-03-15",
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: "Large commercial project",
  },
  {
    id: 255,
    projectName: "Liberty MS",
    location: "Mississippi",
    projectAddress: "Liberty, MS",
    projectLabel: "2025 New Lead",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 100000,
    customer: "Daniel Cothren",
    phone: "(601) 555-7654",
    email: "daniel@example.com",
    buildSize: "10,000 sqft",
    receivedProjectDetails: "2025-01-20",
    zipCode: "39645",
    projectType: "Drive Up",
    projectSQFT: 10000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 107500,
    salesTaxPercent: 0.07,
    ourQuoteWithTax: 116095.68,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 267,
    projectName: "Gunter TX",
    location: "Texas",
    projectAddress: "Gunter, TX",
    projectLabel: "2025 New Lead",
    quoteSent: false,
    reachedOut: true,
    totalCOGs: null,
    customer: "Cane Shumaker",
    phone: "(903) 555-8765",
    email: "cane@example.com",
    buildSize: null,
    receivedProjectDetails: null,
    zipCode: "75058",
    projectType: null,
    projectSQFT: null,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: null,
    salesTaxPercent: null,
    ourQuoteWithTax: null,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 281,
    projectName: "Southgate MI",
    location: "Michigan",
    projectAddress: "Southgate, MI",
    projectLabel: "2025 New Lead",
    quoteSent: false,
    reachedOut: false,
    totalCOGs: null,
    customer: "Dilip Shenoy",
    phone: "(734) 555-9876",
    email: "dilip@example.com",
    buildSize: null,
    receivedProjectDetails: null,
    zipCode: "48195",
    projectType: null,
    projectSQFT: null,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: null,
    salesTaxPercent: null,
    ourQuoteWithTax: null,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 298,
    projectName: "Marine City MI",
    location: "Michigan",
    projectAddress: "Marine City, MI",
    projectLabel: "2025 Active project",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 290000,
    customer: "Matt Iacobacci",
    phone: "(810) 555-1234",
    email: "matt@example.com",
    buildSize: "28,000 sqft",
    receivedProjectDetails: "2025-04-01",
    zipCode: "48039",
    projectType: "Drive Up",
    projectSQFT: 28000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 310000,
    salesTaxPercent: 0.06,
    ourQuoteWithTax: 328600,
    deliveredCustomerQuote: "2025-04-20",
    quoteAcceptedDeclined: "09/03/25",
    depositPaid: "Paid",
    engineeredDrawingsStatus: "Approved",
    estimatedMetalDeliveryDate: "2025-11-01",
    doorOrderSubmittedDate: "2025-09-15",
    estimatedDoorDeliveryDate: "2025-11-20",
    metalProduction: "In production",
    metalDelivery: "Not Yet Delivered",
    doorDelivery: "Not Yet Shipped",
    finalACHPayment: null,
    contractorStartDate: "2025-10-15",
    jobStatus: "In the Works",
    comments: null,
  },
  {
    id: 310,
    projectName: "Buffalo NY",
    location: "New York",
    projectAddress: "Buffalo, NY",
    projectLabel: "2025 New Lead",
    quoteSent: false,
    reachedOut: true,
    totalCOGs: null,
    customer: "Christian Podedworny",
    phone: "(716) 555-2345",
    email: "christian@example.com",
    buildSize: null,
    receivedProjectDetails: null,
    zipCode: "14201",
    projectType: null,
    projectSQFT: null,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: null,
    salesTaxPercent: null,
    ourQuoteWithTax: null,
    deliveredCustomerQuote: null,
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 349,
    projectName: "Bedford Heights OH",
    location: "Ohio",
    projectAddress: "Bedford Heights, OH",
    projectLabel: "2025 Active Bid",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 420000,
    customer: "Brian Mcdermott",
    phone: "(216) 555-3456",
    email: "brian@example.com",
    buildSize: "38,000 sqft",
    receivedProjectDetails: "2025-03-10",
    zipCode: "44146",
    projectType: "Drive Up +CC",
    projectSQFT: 38000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 450000,
    salesTaxPercent: 0.08,
    ourQuoteWithTax: 486000,
    deliveredCustomerQuote: "2025-03-25",
    quoteAcceptedDeclined: null,
    depositPaid: null,
    engineeredDrawingsStatus: null,
    estimatedMetalDeliveryDate: null,
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: null,
    metalProduction: null,
    metalDelivery: null,
    doorDelivery: null,
    finalACHPayment: null,
    contractorStartDate: null,
    jobStatus: null,
    comments: null,
  },
  {
    id: 401,
    projectName: "Casco MI",
    location: "Michigan",
    projectAddress: "Casco, MI",
    projectLabel: "2025 Active project",
    quoteSent: true,
    reachedOut: true,
    totalCOGs: 185000,
    customer: "Steven White",
    phone: "(586) 555-4567",
    email: "steven@example.com",
    buildSize: "18,000 sqft",
    receivedProjectDetails: "2025-05-15",
    zipCode: "48064",
    projectType: "Drive Up",
    projectSQFT: 18000,
    receivedQuoteDrawings: null,
    erectingLabor: null,
    concreteLabor: null,
    ourQuoteMaterialOnly: 198000,
    salesTaxPercent: 0.06,
    ourQuoteWithTax: 209880,
    deliveredCustomerQuote: "2025-06-01",
    quoteAcceptedDeclined: "09/04/25",
    depositPaid: "Paid",
    engineeredDrawingsStatus: "In Progress",
    estimatedMetalDeliveryDate: "2025-12-01",
    doorOrderSubmittedDate: null,
    estimatedDoorDeliveryDate: "2025-12-15",
    metalProduction: "Not Started",
    metalDelivery: "Not Yet Delivered",
    doorDelivery: "Not Yet Shipped",
    finalACHPayment: null,
    contractorStartDate: "2025-11-15",
    jobStatus: "In the Works",
    comments: null,
  },
];

export function getKPIData(): KPIData {
  const totalProjects = projects.length;
  const newLeads = projects.filter(p => p.projectLabel === "2025 New Lead").length;
  const activeBids = projects.filter(p => p.projectLabel === "2025 Active Bid").length;
  const activeProjects = projects.filter(p => p.projectLabel === "2025 Active project").length;
  const quotesAccepted = projects.filter(p => 
    p.quoteAcceptedDeclined && 
    (p.quoteAcceptedDeclined.toLowerCase() === "accepted" || p.quoteAcceptedDeclined.match(/^\d{2}\/\d{2}\/\d{2}$/))
  ).length;
  const depositsPaid = projects.filter(p => p.depositPaid === "Paid").length;
  const totalQuoteValue = projects.reduce((sum, p) => sum + (p.ourQuoteWithTax || 0), 0);

  // Group by label
  const labelCounts: Record<string, number> = {};
  projects.forEach(p => {
    const label = p.projectLabel || "No Label";
    labelCounts[label] = (labelCounts[label] || 0) + 1;
  });
  const projectsByLabel = Object.entries(labelCounts).map(([label, count]) => ({ label, count }));

  // Group by location
  const locationCounts: Record<string, number> = {};
  projects.forEach(p => {
    const location = p.location || "Unknown";
    locationCounts[location] = (locationCounts[location] || 0) + 1;
  });
  const projectsByLocation = Object.entries(locationCounts)
    .map(([location, count]) => ({ location, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 10);

  return {
    totalProjects,
    newLeads,
    activeBids,
    activeProjects,
    quotesAccepted,
    depositsPaid,
    totalQuoteValue,
    projectsByLabel,
    projectsByLocation,
  };
}

export function getProjectById(id: number): Project | undefined {
  return projects.find(p => p.id === id);
}

export function formatCurrency(value: number | null): string {
  if (value === null) return "—";
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(value);
}
